"""Initial schema: create all tables

Revision ID: 120f8e23e14c
Revises:
Create Date: 2026-01-20 17:02:58.134034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "120f8e23e14c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basecom_export_records",
        sa.Column("export_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_status", sa.String(length=50), nullable=True),
        sa.Column("delivery_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("export_id"),
    )
    op.create_index("idx_basecom_export_action", "basecom_export_records", ["action"], unique=False)
    op.create_index(
        "idx_basecom_export_created_at",
        "basecom_export_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_basecom_export_delivery_status",
        "basecom_export_records",
        ["delivery_status"],
        unique=False,
    )
    op.create_table(
        "catalog_state",
        sa.Column("product_id", sa.String(length=255), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "discogs_csv_records",
        sa.Column("record_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_token", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upload_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index("idx_discogs_csv_action", "discogs_csv_records", ["action"], unique=False)
    op.create_index(
        "idx_discogs_csv_created_at",
        "discogs_csv_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_discogs_csv_idempotency_token",
        "discogs_csv_records",
        ["idempotency_token"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_token", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("idx_events_correlation_id", "events", ["correlation_id"], unique=False)
    op.create_index("idx_events_created_at", "events", ["created_at"], unique=False)
    op.create_index("idx_events_idempotency_token", "events", ["idempotency_token"], unique=False)
    op.create_index("idx_events_status", "events", ["status"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(
        "idx_idempotency_created_at",
        "idempotency_records",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "master_catalog",
        sa.Column("external_sku", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("artist", sa.String(length=500), nullable=True),
        sa.Column("format", sa.String(length=100), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("external_sku"),
    )
    op.create_index("idx_master_catalog_release_id", "master_catalog", ["release_id"], unique=False)
    op.create_table(
        "order_inbox",
        sa.Column("inbox_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("idempotency_token", sa.String(length=64), nullable=True),
        sa.Column("airflow_run_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("inbox_id"),
    )
    op.create_index("idx_order_inbox_created_at", "order_inbox", ["created_at"], unique=False)
    op.create_index(
        "idx_order_inbox_idempotency_token",
        "order_inbox",
        ["idempotency_token"],
        unique=False,
    )
    op.create_index("idx_order_inbox_order_id", "order_inbox", ["order_id"], unique=False)
    op.create_index("idx_order_inbox_status", "order_inbox", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_order_inbox_status", table_name="order_inbox")
    op.drop_index("idx_order_inbox_order_id", table_name="order_inbox")
    op.drop_index("idx_order_inbox_idempotency_token", table_name="order_inbox")
    op.drop_index("idx_order_inbox_created_at", table_name="order_inbox")
    op.drop_table("order_inbox")
    op.drop_index("idx_master_catalog_release_id", table_name="master_catalog")
    op.drop_table("master_catalog")
    op.drop_index("idx_idempotency_created_at", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("idx_events_status", table_name="events")
    op.drop_index("idx_events_idempotency_token", table_name="events")
    op.drop_index("idx_events_created_at", table_name="events")
    op.drop_index("idx_events_correlation_id", table_name="events")
    op.drop_table("events")
    op.drop_index("idx_discogs_csv_idempotency_token", table_name="discogs_csv_records")
    op.drop_index("idx_discogs_csv_created_at", table_name="discogs_csv_records")
    op.drop_index("idx_discogs_csv_action", table_name="discogs_csv_records")
    op.drop_table("discogs_csv_records")
    op.drop_table("catalog_state")
    op.drop_index("idx_basecom_export_delivery_status", table_name="basecom_export_records")
    op.drop_index("idx_basecom_export_created_at", table_name="basecom_export_records")
    op.drop_index("idx_basecom_export_action", table_name="basecom_export_records")
    op.drop_table("basecom_export_records")
    # ### end Alembic commands ###
